### ISSUE TITLE
Transformation en plugin pour Home Assistant

### ISSUE THREAD

**Issue by Voileux78** [Aegis940/plugin-teleo#17]
Bonjour,
Merci pour ce plugin Jeedom, qui correspondrait à mes attentes, mais sur Home Assistant... Serait-il possible de le transcrire pour en faire un addon Home Assistant ?
Merci d'avance

**Comment by Aegis940** [comment]
Désolé je ne connais pas HA mais le code du plugin est ouvert donc si quelqu'un veux l'adapter il n'y pas de pb
