### ISSUE TITLE
Remontées dans jeedom absentes

### ISSUE THREAD

**Issue by chrisalex-dev** [Aegis940/plugin-teleo#23]
bonjour,
j'ai bien un contrat veolia idf et un compteur teleo (je peux consulter les conso au quotidien sur le site veolia).
Ceoendant dans jeedom je n'ai aucune remontée. D'où cela peut il venir?

voici ce que je vois dans la log 👍 
ERROR : [Script Python] Message: Service /usr/local/bin/geckodriver unexpectedly exited. Status code was: 1
par avance merci de votre avis.

**Comment by BlacKTM1190** [comment]
Hello
Ca ressemble à un problème de dépendances.
Qu'as-tu dans les logs Teleo_Update ?

**Comment by Aegis940** [comment]
Hello, il faut me donner des détails sur ta configuration : OS, Matériel...
Si tu mets le plugins en debug tu auras plus de log également

Après si tu peux, fais ta demande sur le fourm de jeedom pour capitaliser pour les autres utilisateurs. Merci

**Comment by chrisalex-dev** [comment]
bonjour,
merci de votre retour et voici les logs de teleo_update en pièce jointe.
ma conf est jeedom 4.2.14 sur raspberry pi4b.
sur vos conseil j'ai relancé l'install des dépendances mais cela ne donne rien de mieux.
[teleo_update.txt](https://github.com/Aegis940/plugin-teleo/files/8249376/teleo_update.txt)
.

**Comment by chrisalex-dev** [comment]
bonjour,
j'ai fait une demande d'assistance sur le forum sans succès, pensez vous pouvoir m'aider?
Par avance merci

**Comment by chrisalex-dev** [comment]
bonjour,
j'ai toujours le souci malgré mes recherche sur le forum que j'ai sollicté, pensez vous pourvoir m'aider un peu ou me conseillez vous d'ouvrir un incident chez Jeedom.
Par avance merci

**Comment by Aegis940** [comment]
Hello. Désolé mais le problème vient du driver gecko dont la version disponible n'est pas compatible de debian 10 sous raspberry et il n'y a plus accès aux versions précédentes. Il faudrait que je vous s'il est possible de le recompiler mais là je n'ai pas le bon matériel et le temps. 
Le plugin n'est pas un plugin officiel et le support jeedom ne fonctionnera pas.

**Comment by Aegis940** [comment]
Hello. Normalement fixé dans la dernière version
