### ISSUE TITLE
ERROR : [Script Python] __init__() got an unexpected keyword argument 'firefox_profile'

### ISSUE THREAD

**Issue by chrisalex-dev** [Aegis940/plugin-teleo#52]
bonjour,

depuis le 22 aout je n'arrive plus à remonter les consommation avec le plugin sur jeedom.
Voici le message d'erreur :

[Script Python] Initialisation browser
ERROR : [Script Python] __init__() got an unexpected keyword argument 'firefox_profile'
[Script Python] Taking screenshot : Exception
[Script Python] Fermeture connexion
[Script Python] Fermeture display. Exit code 0
[Script Python] unset $DISPLAY
[Script Python] stdout=b''
[Script Python] stderr=b''

par avance merci de votre support.
Cordialement

**Comment by Aegis940** [comment]
Corrigé dans la dernière version (nécessite selenium 4.13 ou +)
